### ISSUE TITLE
Figure 1: maps

### ISSUE THREAD

**Issue by rvanmazijk** [tle003/Schoenus-phylogeny#13]
- [x] **(a) Global _Schoenus_ species richness in [TDWG](http://tdwg.org/) regions**
    - [x] Data from @tle003 
    - [x] Code @tle003 
    - [x] Try duller yellow or pale green for low richness (comment from @tle003)
- [x] **(b) Global _Schoenus_ sampling effort**
    - [x] Data and calculations by @tle003 
    - [x] Code and calculations by @rvanmazijk 
- [x] **(c) South African _Schoenus_ species richness in QDGCs**
    - [x] Data from @tle003 
    - [x] Code by @rvanmazijk 
    - [x] Use African continental border to get coastline, a.o.t. "floating" South African border, then crop to same extent as South African border
- [x] **(d) Australia and New Zealand (#5) _Schoenus_ species richness in QDGCs**
    - [x] Data from Australian collaborators, collated into QDGC by @rvanmazijk 
    - [x] Code by @rvanmazijk 
    - [x] Perhaps the sampling there is too poor also, and thus New Caledonia should be excluded (#7)?
    - ~~#6?~~ Nah. Sampling in Indonesia and Papua New Guinea too poor.
- [x] Code for each panel integrated together by @rvanmazijk 
- [x] Re: (c) and (d), perhaps rather use full-resolution border shapefiles, as some bits of coastline and small islands are absent otherwise, despite being in our occurrence data
- [x] Re: all, rather than having "Longitude (º)" and "Latitude (º)" axis labels, have º-symbol in axis numbering?

**Comment by rvanmazijk** [comment]
- [ ] Re: #7, perhaps the sampling there is too poor also, and thus New Caledonia should be excluded?

**Comment by rvanmazijk** [comment]
- [ ] Re: (b) and (c), perhaps rather use full-resolution border shapefiles, as some bits of coastline and small islands are absent otherwise, despite being in our occurrence data.
